{{- if not .Values.existingSecret }}
{{- $fullName := include "caluma.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-backend
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  secretkey: {{ if .Values.secretKey }}{{ .Values.secretKey | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{- end }}
